global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'erpc'
    static_configs:
      - targets: ['REPLACE_SERVICE_ENDPOINT_HERE:REPLACE_SERVICE_PORT_HERE']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093